name: lerno

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: lernoStorage
    ports:
      - "54321:5432"
  
  rabbit:
    image: rabbitmq:3.13-management
    hostname: lerno-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: kuzichkinpa
      RABBITMQ_DEFAULT_PASS: qwe123
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    depends_on:
      - db

  redis:
    image: redis
    hostname: redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    depends_on:
      - db

  redis-commander:
    image: rediscommander/redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    
    depends_on:
      - redis
